flags:
  buildsome:
    Charts: False
packages:
- location: https://github.com/da-x/happy/archive/8ab3b312c38ff9ac222d96fc4df36ce10cf8f639.zip
  extra-dep: true
- .
extra-deps:
- leveldb-haskell-0.6.3
resolver: lts-3.0
rebuild-ghc-options: true